[package]
name = "dds"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "1.3"
byteorder = "1.4"
bytemuck = { version = "1.7", features = ["extern_crate_std", "derive"] }
thiserror = "1.0"
num_enum = "0.5"
wgpu = "0.11"
